import os
import boto3
from pygame import mixer

polly = boto3.client('polly')


introText = "<speak>Welcome to the Historical European Martial Arts training. Together, we will train the German Longsword techniques, created by the 14th-century fencing master, <lang xml:lang=\"de-DE\">Johannes Liechtenauer</lang>. I utilize cloud computing and deep learning, to score you on your technique, using real time data generated by your swords' sensors. I will call for a guard or a strike, and you can execute it. So, grab your sword! We start in: 3. 2. 1.</speak>"
introSpokenText = polly.synthesize_speech(Text = introText, OutputFormat='mp3', VoiceId = 'Brian', TextType='ssml')
with open('intro.mp3', 'wb') as f:
	f.write(introSpokenText['AudioStream'].read())
	f.close()

mixer.init()
mixer.music.load('intro.mp3')
mixer.music.play()
while mixer.music.get_busy() == True:
	pass
mixer.quit()
os.remove('intro.mp3')


outroText = "<speak>Guards: <lang xml:lang=\"de-DE\">Vom tag. Ochs. Pflug. Alber.</lang> Strikes: <lang xml:lang=\"de-DE\">Mittelhaw. Underhaw. Oberhaw.</lang> Session complete! Your score is: 62%. Now, I can use your data to also become better at grading you. Thank you for using longsword training.</speak>"
outroSpokenText = polly.synthesize_speech(Text = outroText, OutputFormat='mp3', VoiceId = 'Brian', TextType='ssml')
with open('outro.mp3', 'wb') as f:
        f.write(outroSpokenText['AudioStream'].read())
        f.close()

mixer.init()
mixer.music.load('outro.mp3')
mixer.music.play()
while mixer.music.get_busy() == True:
        pass
mixer.quit()
os.remove('outro.mp3')
